### ISSUE TITLE
Configuration section for output

### ISSUE THREAD

**Issue by cognitivegears** [get-woke/woke#124]
**Is your feature request related to a problem? Please describe.**
Not a problem, exactly, though currently the "Success Error Message" doesn't make sense by itself, as the output of that could/should vary per output type. Also, without an output section in the config I was unable to add "effortMinutes" to the sonarqube output since that is likely to vary per team.

**Describe the solution you'd like**
I'd like to see a section of the configuration file for output configuration (per file type.) Something like:

output:
    - type: text
    exitCodeOnFindings: 1
    printColor: true
    includeOriginalLine: true
    successMessage: "No findings found. YAY!"
    - type: sonarqube
    exitCodeOnFindings: 0
    sonarEffortMinutes: 10

**Describe alternatives you've considered**
None - this would just add additional functionality for the system.

**Additional context**
I've been thinking about two other output types that could be useful - CSV (for importing into Excel, etc) and HTML (to give a pretty report for viewing/printing). Both of theses formats could also use additional output options (whether to include headings for CSV, and template locations etc for HTML.) I'll put in a separate Feature Request or PR for these, but these are just examples of other types that could use an output section. In addition, with this change I think we could also potentially collapse the simple and text outputs into a single output type if that is desirable.

**Comment by caitlinelfring** [comment]
Do you have any other linters that you can point to that have similar features? I'd like for this project to remain consistent with other linters and not try to reinvent the wheel. 

-1 on the html printer, since there is a lot more nuance and opinion on visual displays of html that I would prefer to leave out of woke. I would say the right place for this is in an external tool. Pretty sure the same can be said about CSV as well. 

Something like `woke > output.json; json2html output.json > output.html`

I'll have to think some more about your output schema

**Comment by cognitivegears** [comment]
Got you. I cannot think of one offhand, though the difference with other linters I think is that in my mind I'm hoping to use this not just for maintaining quality over time, but also the ability to remediate (large) legacy codebases as well. For most linters, I probably wouldn't go back and try to change a large existing codebase, but rather as a quality check going forward. In this case I think of it having more in common with something like a static analysis security tool, where you would use it both initially to remediate issues in existing code as well as ongoing to keep new issues from cropping up. And from that case, reporting-like features are helpful for that initial investigation / reporting on the initial efforts etc.

All that said, what you propose with a second tool makes a lot of sense and is a great way forward, and does fit well with the Unix do one thing well type design. I'll think about ways to still promote the use case above, maybe separate how-to articles or something.

**Comment by cognitivegears** [comment]
Ha! Funny timing, I just saw a post announcing this:

https://mmalcek.github.io/bafi/

A tool (written in Go) for converting between input and output formats - i.e. json to csv, html, xml, etc.

To that end, I guess the only thing that would be useful here still would be the option to have the json output in a single valid json object so that it can be consumed by this (or similar) tools.
