### ISSUE TITLE
Implementation question

### ISSUE THREAD

**Issue by jamescoll** [get-woke/woke#153]
**Is your feature request related to a problem? Please describe.**

I’m just wondering if you could take a moment to add how governance for this product is done. Who/whom decides which particular words must be struck out and who decides which are included? It seems to me - naively - that working out without context - which words may or may not offend (or make feel included) any of 7 billion people, many hundreds of languages, vast amounts of cultural differences and a huge diversity (old meaning - meaning “difference in substance” not new meaning “difference in appearance or sexual preference/identity”) is a really hard problem requiring global expertise and a vast team of linguistic experts. How did you manage that? Words - over time and through context - accrue a staggering number of potential meanings - sometimes - as in the case of “silly” acquiring the reverse meaning to their original (in so far as we can know it) form (it likely meant “blessed” in older English). It must take a huge amount of perception and genius to sift through all of this. How is it done?

https://www.etymonline.com/word/silly

**Describe the solution you'd like**

A clear and concise description of how which words are “non-inclusive” and which words are “inclusive” is decided and how that decision is normalised globally across culture and contexts. And how tie breaks are resolved where one community may find one word non- inclusive and another may not (given the vast range of possible offences that may be caused across communities - this is a non trivial problem). Also what is done about words which may not be offensive in English but which if taken as Spanish words - for example - could possibly offend someone - that seems tricky too.

**Describe alternatives you've considered**

I haven’t - I don’t think this problem is practically solvable. Frank discussion between individuals as individuals generally works well though.

**Additional context**

Cf On Liberty - John Stuart Mill, the later works of George Orwell, The Open Society and its Enemies by Popper, any decent history of 20th century communism, Cynical Theories by Lindsay and Pluckrose ... etc...

**Comment by cognitivegears** [comment]
The tool itself does not enforce any particular word list. The company/project/organization/individual is free to make their own list via the Woke configuration, as well as to set the descriptions, alternative terms, and severity. While Woke includes a default list, it is really useful more as an example more than anything.

**Comment by jamescoll** [comment]
Hi - thanks for the reply - I appreciate it. My comment was made really
just to ensure you are aware of the dangers of tools like this and also how
they could empower some of the worst types of people in organizations.

We are living in a moment when people are increasingly being seen as
identities rather than individuals in organisations and when words rather
than intentions are being seen as dangerous. That carries a number of
dangers which used to be obvious and even the term woke itself is rife with
controversy which matters mostly only if one isn’t aware of it. In addition
- it is a very hard problem to determine what is offensive speech outside
of context as a number of key cases in the US show.

It was hard for even a Supreme Court justice to define pornography so how
can we hope to define inclusive or exclusive speech.  We only come to
common agreement on a very, very small number of terms. A tool like this in
the hands of the wrong person could be hugely problematic and I fail to see
how - especially in the context of a code review - an exchange between two
people mindful of intentionally and context - would be trumped by a tool
set by folks who could have an entirely different mindset.

This is clearly different when someone sets out to deliberately offend
another - this kind of thing - in my experience - in a corporate context -
is very rare although it for sure happens.

Imagine a future in which an engineer is writing this data structure and is
pulled aside because a committee of well minded non technical folks decided
it was non-inclusive or racist “white grey black tree”

https://levelup.gitconnected.com/the-white-grey-black-tree-b9a96f12e9e9?gi=df983b702b08

Or someone implements a “lazy load” and someone objects to the term because
it sounds pejorative.

https://www.imperva.com/learn/performance/lazy-loading/


Or someone talks about a “race condition” and that sounds like it might
have something to do with ethnicity so that’s gotta go.

https://en.m.wikipedia.org/wiki/Race_condition

And then there’s a “crash dump”

https://en.m.wikipedia.org/wiki/Core_dump

Or a “hang” ...

https://en.m.wikipedia.org/wiki/Hang_(computing)

So the problem here is combined of two contradictory problems - hammers
only see nails (so those looking for offence will surely find it) and
language has a property of not hanging around for anyone to decide what it
means. Hence we consider the intention as well as the action.

https://www.iclr.co.uk/knowledge/glossary/mens-rea-and-actus-reus/

I think anyone who puts themselves out there to make and release an open
source tool is a badass (is that non inclusive) btw. So nice skillz 🤘 but
there be dragons in stuff like this.

**Comment by caitlinelfring** [comment]
I appreciate your input, but this is not the forum for such a discussion. Please review the [contributing guidelines](https://github.com/get-woke/woke/blob/main/CONTRIBUTING.md) for this repo.

I recommend reaching out to the Inclusive Naming Initiative https://inclusivenaming.org/

**Comment by jamescoll** [comment]
Hi

Cool. Where can we discuss?

J
