### ISSUE TITLE
SonarQube output format startColumn needs to be zero based

### ISSUE THREAD

**Issue by karlajw** [get-woke/woke#161]
Thank you for creating the issue!

- [x ] Yes, I've searched similar issues on GitHub and didn't find any.
- [x ] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of woke</summary>

0.15.0, 0.15.1, 0.16.1

</details>

<details><summary>Config file</summary>

default config

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
# paste output here
```

</details>

<details><summary>Verbose output of running</summary>
</details>

Woke generated an issue report that has the same value of 'startColumn' and 'endColumn' (both with a value of 1) when there is only one column (ie. file name, java package name)

{
  "issues":[
    {
      "engineId":"woke",
      "ruleId":"dummy",
      "primaryLocation":{
         "message":"Filename finding: `dummy` may be insensitive, use `placeholder`, `sample` instead",
        "filePath":"src/main/java/com/testco/pocproject/dummy",
        "textRange":{
          "startLine":1,
          "startColumn":1,
          "endColumn":1
        }
      },
      "type":"CODE_SMELL",
      "severity":"MAJOR"
    },

......

  ]
}

SonarQube throws the following runtime error when trying to import the above issue format:

ERROR: Error during SonarScanner execution
      java.lang.IllegalArgumentException: Start pointer [line=1, lineOffset=1] should be before end pointer [line=1, lineOffset=1]

SonarQube documentation shows the startColumn field as zero based https://docs.sonarqube.org/latest/analysis/generic-issue/

The Hadolint project has had a similar issue eg. https://github.com/hadolint/hadolint/issues/658

**Comment by cognitivegears** [comment]
I've duplicated this issue with a local Sonarqube instance. This happens for file/path results where the start index and end index are both set to 1. Sonarqube doesn't like having these set to the same value and fails to import. Created a potential fix as #162  and added a test to expose / validate the issue resolution.

**Comment by karlajw** [comment]
Thanks for the quick fix!

**Comment by caitlinelfring** [comment]
Released in https://github.com/get-woke/woke/releases/tag/v0.17.1

**Comment by caitlinelfring** [comment]
Thanks for the quick fix @cognitivegears!!!
