### ISSUE TITLE
Installer script doesn't understand `linux/arm64`

### ISSUE THREAD

**Issue by skyzyx** [get-woke/woke#199]
Thank you for creating the issue!

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, config, etc).

----

Inside an Alpine Linux Docker container running on my M1-based Mac, I am trying to install Woke. From my `Dockerfile`:

```Dockerfile
RUN curl -sSLf https://git.io/getwoke | bash -s -- -b /usr/local/bin
```

I receive the following error during `docker build`:

> get-woke/woke crit platform linux/arm64 is not supported.  Make sure this script is up-to-date and file request at https://github.com/get-woke/woke/issues/new

Looks like the installer script doesn't understand `linux/arm64`, even though you publish the packages in the releases.

**Comment by caitlinelfring** [comment]
Can you try running with debug logging on and post the output? `curl -sSLf https://git.io/getwoke | bash -s -- -b /usr/local/bin -d`

**Comment by caitlinelfring** [comment]
@skyzyx I have a fix up in #200 for this, but can you verify your issue is resolved by running `curl -sSLf https://raw.githubusercontent.com/get-woke/woke/issue/199/install.sh | bash -s -- -b /usr/local/bin -d` and posting the output? (the `-d` at the end enabled debug logging and isn't necessary once this PR is merged).

**Comment by skyzyx** [comment]
Testing…

**Comment by skyzyx** [comment]
On Alpine Linux:

```bash
$ apk add curl bash
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/aarch64/APKINDEX.tar.gz
(1/9) Installing ncurses-terminfo-base (6.3_p20220521-r0)
(2/9) Installing ncurses-libs (6.3_p20220521-r0)
(3/9) Installing readline (8.1.2-r0)
(4/9) Installing bash (5.1.16-r2)
Executing bash-5.1.16-r2.post-install
(5/9) Installing ca-certificates (20211220-r0)
(6/9) Installing brotli-libs (1.0.9-r6)
(7/9) Installing nghttp2-libs (1.47.0-r0)
(8/9) Installing libcurl (7.83.1-r1)
(9/9) Installing curl (7.83.1-r1)
Executing busybox-1.35.0-r13.trigger
Executing ca-certificates-20211220-r0.trigger
OK: 10 MiB in 23 packages

$ curl -sSLf https://raw.githubusercontent.com/get-woke/woke/issue/199/install.sh | bash -s -- -b /usr/local/bin -d
get-woke/woke info checking GitHub for latest tag
get-woke/woke debug http_download https://github.com/get-woke/woke/releases/latest
get-woke/woke info found version: 0.18.2 for v0.18.2/linux/arm64
get-woke/woke debug downloading files into /tmp/tmp.ljiInc
get-woke/woke debug http_download https://github.com/get-woke/woke/releases/download/v0.18.2/woke-0.18.2-linux-arm64.tar.gz
get-woke/woke debug http_download https://github.com/get-woke/woke/releases/download/v0.18.2/woke-0.18.2-checksums.txt
get-woke/woke info installed /usr/local/bin/woke
```

Seems to work now. Thanks!

**Comment by skyzyx** [comment]
From your _first_ response:

> Can you try running with debug logging on and post the output? `curl -sSLf https://git.io/getwoke | bash -s -- -b /usr/local/bin -d`

```bash
$ curl -sSLf https://git.io/getwoke | bash -s -- -b /usr/local/bin -d
get-woke/woke crit platform linux/arm64 is not supported.  Make sure this script is up-to-date and file request at https://github.com/get-woke/woke/issues/new
```

This was the message I saw when first putting together my `Dockerfile`.

**Comment by caitlinelfring** [comment]
Using them install instructions in the docs should work now. Thanks for reporting!

**Comment by skyzyx** [comment]
Thanks for fixing!
