### ISSUE TITLE
Add multiarch support to container image

### ISSUE THREAD

**Issue by sxd** [get-woke/woke#215]
**Describe the solution you'd like**
GoReleaser should support the build of container manifest with the multiarch images insides

**Additional context**
GoReleaser already support docker manifest for this, and this will help to run the woke
container inside a Raspberry Pi 4

**Comment by caitlinelfring** [comment]
@sxd This has been released in [`v0.18.4`](https://github.com/get-woke/woke/releases/tag/v0.18.4). Thanks so much for your contribution!!!

**Comment by sxd** [comment]
@caitlinelfring thank you! already checked and it works! I'll try to contribute more!
