### ISSUE TITLE
Apply wokeignore rules on their own line to the following line

### ISSUE THREAD

**Issue by MatthewRyanRead** [get-woke/woke#42]
**Is your feature request related to a problem? Please describe.**
In some of our projects, we use Google Java Format.  This disallows end-line comments, so an alternative to end-line `wokeignore` comments would be ideal.  Some SQL interpreters also disallow end-line comments, and I'm sure there are other languages/tools that behave the same way.

**Describe the solution you'd like**
The ability to have `wokeignore` comments apply to the following line would be great.  I know `woke` doesn't understand language conventions for comments, so I was thinking of something like: If no characters on the line (apart from those composing the `wokeignore:rule=<rule list>` string) are alphabetic characters, then apply the rule to the next line.  This would cover `<!-- comment -->`, `# comment`, `-- comment`, `// comment`, etc.

In C++, this could be done with [iswalpha()](https://en.cppreference.com/w/cpp/string/wide/iswalpha).  Hopefully there is something similar in Go.

**Describe alternatives you've considered**
None.

**Additional context**
N/A

**Comment by caitlinelfring** [comment]
Thanks for the feature request! I agree, and since `yamllint` has similar functionality https://yamllint.readthedocs.io/en/stable/disable_with_comments.html, I think it's something woke should be able to support.

**Comment by pcmxgti** [comment]
`Dockerfile` is another place where inline comments are not allowed. It would be very helpful to me if the feature that covers @MatthewRyanRead's request works for Docker as well.

**Comment by caitlinelfring** [comment]
This feature has been released in [`v0.12.0`](https://github.com/get-woke/woke/releases/tag/v0.12.0).
