### ISSUE TITLE
Add checks for filenames

### ISSUE THREAD

**Issue by markusthoemmes** [get-woke/woke#6]
**Is your feature request related to a problem? Please describe.**
Sometimes, offending words aren't only used **inside** files but also for their names, e.g. `whitelist_test.go`.

**Describe the solution you'd like**
We should check that too, probably reporting the issue as line 1 in the file to stay compatible with reviewdog etc.

**Describe alternatives you've considered**
I've done that through grep and friends but... meh.

---

This tool is awesome :slightly_smiling_face:. I'd be happy to take a crack at implementing the file name checking if you're accepting PRs.

**Comment by caitlinelfring** [comment]
Great suggestion, thank you! Will look into it

**Comment by caitlinelfring** [comment]
@markusthoemmes I just put up a PR (#10) that will show a different description if there's a filename violation, on line 1, column 1, to make it clear that it's a violation for the filename, not the line in the file. You can see it here: https://github.com/get-woke/woke/pull/10/files#diff-445bfbe0456fcdfc25f8761baf1934e4

Would love to hear your thoughts!
