### ISSUE TITLE
Fix replacement suggestions for blacklist / whitelist

### ISSUE THREAD

**Issue by Nytelife26** [get-woke/woke#65]
It is apparent that this project has fallen under an inconsiderate paradigm in regards to the replacement of "blacklist" / "whitelist" terminology. Replacements such as "allowlist" are not viable unfortunately.

This is not the only organization, of course, so no blame is on the developers. I am part of a group of people seeking to spread awareness on this :)

For more information, see:
- [The ongoing INI discussion](https://github.com/inclusivenaming/website/pull/45)
- [A pull request to Google's v8 engine](https://github.com/v8/v8.dev/pull/537)
- [The Kludge Cyber Systems open statement](https://github.com/kludge-cs/transparency/blob/master/open-statements/2021-04-04--TERMINOLOGY.md)

Thank you in advance for your time.

**Comment by caitlinelfring** [comment]
Thank you for bringing awareness to this topic! I didn't know about https://inclusivenaming.org/ and will look into it further and see how I can apply recommendations to woke.

**Comment by Nytelife26** [comment]
> Thank you for bringing awareness to this topic! I didn't know about https://inclusivenaming.org/ and will look into it further and see how I can apply recommendations to woke.

No worries, always happy to help. Our discussions have concluded mostly that "exclusion list" and "inclusion list" are better replacements, if that helps - however, it is largely contextual.

**Comment by Nytelife26** [comment]
@caitlinelfring That doesn't really solve much. The point is that allowlist and blocklist are fundamentally poor choices, and create more harm than good. We should strive to use better alternatives where possible, and I don't think keeping around poor solutions is a good thing.

**Comment by caitlinelfring** [comment]
I read through the conversations in the links you provided and I believe the change I made is sufficient. This seems like more of a general conversation that I would expect the community as a whole to resolve, not this specific tool. 

I would also like to point you to our [Contributing Guidelines](https://github.com/get-woke/woke/blob/main/CONTRIBUTING.md), specifically:

> This project is not the forum to determine what is inclusive language and what is insensitive language. Contributions should be limited to providing consumers of woke the ability to make their own decisions regarding conscious language.

Again, I appreciate you bringing this topic up, but until there is a concrete, widely-accepted solution, I don't believe there is much else to be done here at this point in time. Allowlist and denylist, while they may not be perfect alternatives, are not offensive.

**Comment by Nytelife26** [comment]
> Again, I appreciate you bringing this topic up, but until there is a
> concrete, widely-accepted solution, I don't believe there is much else
> to be done here at this point in time. Allowlist and denylist, while
> they may not be perfect alternatives, are not offensive.

Whether something is offensive or not is not the qualifier for
inclusivity. Inclusivity also means accessibility.

But, thank you for your time and consideration anyways. I appreciate it.
You were the fastest to actually do something out of all the people I
spoke to.
