### ISSUE TITLE
`grandfathered` alternatives are confusing

### ISSUE THREAD

**Issue by mxmeinhold** [get-woke/woke#70]
I've seen `grandfathered` and `grandfathered in` as verbs (e.g. [the wiki page for Grandfather clause](https://en.wikipedia.org/wiki/Grandfather_clause)), and I don't think the alternative of `legacy status` serves as a good replacement. I'm not sure `legacy status` really captures what I understand `grandfathered` to mean ("allowed even though it is out of line with current policy because it existed prior to the implementation of current policy"). Perhaps `deprecated`, though that has other implications? I'm sorry, I don't have a clear suggestion at the moment, but I wanted to bring it up for the chance at a discussion before I forgot about it.
https://github.com/get-woke/woke/blob/576b42ae8fb499c6b9c12bd827d9a087ede26365/pkg/rule/default.yaml#L41-L45

**Comment by caitlinelfring** [comment]
I am going to close this issue since there hasn't been any activity in a few months. I will reopen if there is interest
