### ISSUE TITLE
Use word boundaries (\b) or ChangeInCase to reduce false positives

### ISSUE THREAD

**Issue by danbeam** [get-woke/woke#80]
I have a "redline" rule in a woke config.

* https://www.washingtonpost.com/news/wonk/wp/2018/03/28/redlining-was-banned-50-years-ago-its-still-hurting-minorities-today/
* https://en.wikipedia.org/wiki/Redlining
* https://www.investopedia.com/terms/r/redlining.asp

However, in some code, I found this example that I don't believe should be causing a violation (IMO):
```ts
const measuredLineHeight = getComputedStyle(el).lineHeight;
```

Which contains the substring, but I think might have enough signal to not marked.

- [x] Yes, I've searched similar issues on GitHub and didn't find any.

Kinda, https://github.com/get-woke/woke/issues/58 is similar-ish (except that in my case I do want the code to be checked).

- [x] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of woke</summary>

```console
$ woke --version
woke version 0.9.0
```

</details>

<details><summary>Config file</summary>

```console
$ cat .woke.yml
rules:
  - name: redline
    terms:
      - redline
    alternatives:
      - annotate
```

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
go: command not found
```

</details>

<details><summary>Verbose output of running</summary>

```console
$ woke --debug
2021-05-25T10:18:40-07:00 DBG woke version 0.9.0 built from 4e1a9a0 on 2021-05-22T15:23:11Z
2021-05-25T10:18:40-07:00 DBG loaded config file config=/path/to/woke-repro/.woke.yml
2021-05-25T10:18:40-07:00 DBG rules enabled rules=["redline","whitelist","blacklist","master-slave","slave","grandfathered","man-hours","sanity","dummy","guys","whitebox","blackbox"]
2021-05-25T10:18:40-07:00 DBG skipping ignorefile error="open .gitignore: no such file or directory" file=.gitignore
2021-05-25T10:18:40-07:00 DBG skipping ignorefile error="open .wokeignore: no such file or directory" file=.wokeignore
2021-05-25T10:18:40-07:00 DBG finished compiling ignores durationMS=0.127734
2021-05-25T10:18:40-07:00 DBG created new printer printer=text
2021-05-25T10:18:40-07:00 DBG process files path=. type=parallel
2021-05-25T10:18:40-07:00 DBG skipping file=.woke.yml reason="ignored file"
2021-05-25T10:18:40-07:00 DBG skipping content file=. reason="file is a directory"
2021-05-25T10:18:40-07:00 DBG finished processing violations durationMS=0.191194 file=.
2021-05-25T10:18:40-07:00 DBG finished processing violations durationMS=0.126851 file=test.js
test.js:1:11-18: `redLine` may be insensitive, use `annotate` instead (error)
const measuredLineHeight = getComputedStyle(el).lineHeight;
           ^
2021-05-25T10:18:40-07:00 DBG woke completed durationMS=1.012913
```

</details>

**Comment by caitlinelfring** [comment]
There is a word boundary option that you can set on a per-rule basis https://github.com/get-woke/woke#options. Would this help?

**Comment by danbeam** [comment]
> There is a word boundary option that you can set on a per-rule basis https://github.com/get-woke/woke#options. Would this help?

thanks for point this out; didn't know about it.  i'll give it a go.

**Comment by bachand** [comment]
I did not know about the word boundary option that can be added per rule. Neat!

I see from the [code](https://github.com/get-woke/woke/blob/4e1a9a0fd5f487ae431607d2714ba3f7b14e7057/pkg/rule/rule.go#L97) that the word boundary options creates a regex like `\b(TERM)\b` where `TERM` is the original term.

If we consider a term like "whitelist", it would be great if there were a way for "whitelist" to match "whitelist", "whitelister", and "whitelisted". Then we'd also include "whiteList" as a term to cover "whiteList", "whiteLister", and "whiteListed".

<img width="398" alt="Screen Shot 2021-06-04 at 7 09 06 PM" src="https://user-images.githubusercontent.com/1791049/121265436-a5961900-c86d-11eb-84ee-dbfd16f56017.png">

**Comment by caitlinelfring** [comment]
Would you be interested in the ability to set options like `word_boundary_start` and `word_boundary_end` to provide more granular regex? We could even go as far as allowing the regex to be completely customizable. Thoughts?

**Comment by bachand** [comment]
How about we start with the option to specify the start and end of the word boundary, for simplicity.

**Comment by caitlinelfring** [comment]
@danbeam @bachand I opened a PR to add `word_boundary_start` and `word_boundary_end` options for a rule https://github.com/get-woke/woke/pull/100

**Comment by caitlinelfring** [comment]
Released in https://github.com/get-woke/woke/releases/tag/v0.10.0

**Comment by Puneethgr** [comment]
For better clarity, please add an example for the options ```word_boundary```, ```word_boundary_start```, and ```word_boundary_end``` in the documentation (https://docs.getwoke.tech/rules/#options) 
Thank you @caitlinelfring
