### ISSUE TITLE
Name change 

### ISSUE THREAD

**Issue by 0x00009b** [get-woke/woke#92]
The term "Woke" is  ableist and non inclusive word, and excludes people with narcolepsy and may make them feel bad and/or hurt.

suggested change:
Change project name to "inclusive language tool"

Other possible changes: 
- adding a trigger warning at the top of the repo.

**Comment by caitlinelfring** [comment]
I appreciate the feedback, this is the first I've heard of the term "woke" being non-inclusive and ableist, but I am empathetic and want to remain inclusive. Thanks for commenting and I might consider a note at the readme. 

I want to note the origins of the term `woke` and where the tool gets its name from: https://en.wikipedia.org/wiki/Woke.
